name: Format with Spotless

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Format using spotless
      run: ./gradlew spotlessApply
    - name: Stage all changes
      run: git add .
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Format with spotless
